# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kjell/fpga_dev/fpga_mcu_main/constr/config.xdc

# XDC: /home/kjell/fpga_dev/fpga_mcu_main/constr/pinout.xdc

# XDC: /home/kjell/fpga_dev/fpga_mcu_main/constr/pinout_prohibit.xdc

# XDC: /home/kjell/fpga_dev/fpga_mcu_main/constr/chipscope.xdc

# XDC: /home/kjell/fpga_dev/fpga_mcu_main/constr/ip_correction.xdc

# Block Designs: bd/mcu/mcu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu || ORIG_REF_NAME==mcu}]

# IP: bd/mcu/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}]

# IP: bd/mcu/ip/mcu_axi_timer_0_0/mcu_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_timer_0_0 || ORIG_REF_NAME==mcu_axi_timer_0_0}]

# IP: bd/mcu/ip/mcu_c_counter_binary_0_0/mcu_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_c_counter_binary_0_0 || ORIG_REF_NAME==mcu_c_counter_binary_0_0}]

# IP: bd/mcu/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}]

# IP: bd/mcu/ip/mcu_mdm_1_0/mcu_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_mdm_1_0 || ORIG_REF_NAME==mcu_mdm_1_0}]

# IP: bd/mcu/ip/mcu_microblaze_0_0/mcu_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_0 || ORIG_REF_NAME==mcu_microblaze_0_0}]

# IP: bd/mcu/ip/mcu_microblaze_0_axi_intc_0/mcu_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mcu_microblaze_0_axi_intc_0}]

# IP: bd/mcu/ip/mcu_microblaze_0_axi_periph_0/mcu_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mcu_microblaze_0_axi_periph_0}]

# IP: bd/mcu/ip/mcu_xbar_0/mcu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_xbar_0 || ORIG_REF_NAME==mcu_xbar_0}]

# IP: bd/mcu/ip/mcu_dlmb_bram_if_cntlr_0/mcu_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mcu_dlmb_bram_if_cntlr_0}]

# IP: bd/mcu/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_dlmb_v10_0 || ORIG_REF_NAME==mcu_dlmb_v10_0}]

# IP: bd/mcu/ip/mcu_ilmb_bram_if_cntlr_0/mcu_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mcu_ilmb_bram_if_cntlr_0}]

# IP: bd/mcu/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_ilmb_v10_0 || ORIG_REF_NAME==mcu_ilmb_v10_0}]

# IP: bd/mcu/ip/mcu_lmb_bram_0/mcu_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_lmb_bram_0 || ORIG_REF_NAME==mcu_lmb_bram_0}]

# IP: bd/mcu/ip/mcu_microblaze_0_xlconcat_0/mcu_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mcu_microblaze_0_xlconcat_0}]

# IP: bd/mcu/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}]

# IP: bd/mcu/ip/mcu_util_reduced_logic_0_0/mcu_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_util_reduced_logic_0_0 || ORIG_REF_NAME==mcu_util_reduced_logic_0_0}]

# IP: bd/mcu/ip/mcu_xlslice_0_0/mcu_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_xlslice_0_0 || ORIG_REF_NAME==mcu_xlslice_0_0}]

# IP: bd/mcu/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}]

# IP: bd/mcu/ip/mcu_axi_iic_0_0/mcu_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_iic_0_0 || ORIG_REF_NAME==mcu_axi_iic_0_0}]

# XDC: bd/mcu/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_axi_timer_0_0/mcu_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_timer_0_0 || ORIG_REF_NAME==mcu_axi_timer_0_0}]

# XDC: bd/mcu/ip/mcu_axi_timer_0_0/mcu_axi_timer_0_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_c_counter_binary_0_0/mcu_c_counter_binary_0_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_mdm_1_0/mcu_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_mdm_1_0 || ORIG_REF_NAME==mcu_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_mdm_1_0/mcu_mdm_1_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_microblaze_0_0/mcu_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_0 || ORIG_REF_NAME==mcu_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_microblaze_0_0/mcu_microblaze_0_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_microblaze_0_axi_intc_0/mcu_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mcu_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_microblaze_0_axi_intc_0/mcu_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mcu_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_microblaze_0_axi_intc_0/mcu_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_xbar_0/mcu_xbar_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_dlmb_bram_if_cntlr_0/mcu_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_dlmb_v10_0 || ORIG_REF_NAME==mcu_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_ilmb_bram_if_cntlr_0/mcu_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_ilmb_v10_0 || ORIG_REF_NAME==mcu_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_lmb_bram_0/mcu_lmb_bram_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}]

# XDC: bd/mcu/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}]

# XDC: bd/mcu/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mcu/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu/ip/mcu_axi_iic_0_0/mcu_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_iic_0_0 || ORIG_REF_NAME==mcu_axi_iic_0_0}]

# XDC: bd/mcu/ip/mcu_axi_iic_0_0/mcu_axi_iic_0_0_ooc.xdc

# XDC: bd/mcu/mcu_ooc.xdc
