webtalk_init -webtalk_dir /home/kjell/fpga_dev/fpga_mcu_main/sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 25 23:28:42 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210891984_1777499880_210580059_069" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aespotj9nt4lou1l3kv0lrv0el" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594.009 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1424900881000" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key Device -value "7a200t" -context "sdk\\\\hardware/1424900881000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1424900881000"
webtalk_transmit -clientid 3581375342 -regid "210891984_1777499880_210580059_069" -xml /home/kjell/fpga_dev/fpga_mcu_main/sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/kjell/fpga_dev/fpga_mcu_main/sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/kjell/fpga_dev/fpga_mcu_main/sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
